[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_add = '''
  nnoremap <silent>sf :<C-u>Defx -listed -resume -buffer-name=tab`tabpagenr()`<CR>
'''
hook_source = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = '''
  # source ~/.config/nvim/plugins/denite.rc.vim
# '''

[[plugins]]
repo = 'fatih/vim-go'
rev = 'release'
on_ft = 'go'
