[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'flrnprz/plastic.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
