[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_add = '''
  nnoremap <silent>sf :<C-u>Defx -listed -resume -buffer-name=tab`tabpagenr()`<CR>
'''
hook_source = 'source ~/.config/nvim/plugins/defx.rc.vim'
hook_post_update = 'UpdateRemotePlugins'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'nvim-lua/plenary.nvim'
# 
# [[plugins]]
# repo = 'nvim-telescope/telescope.nvim'
# depends = ['plenary.nvim']
# hook_source = 'source ~/.config/nvim/plugins/telescope.rc.vim'
# 
# [[plugins]]
# repo = 'Shougo/denite.nvim'
# hook_add = '''
  # source ~/.config/nvim/plugins/denite.rc.vim
# '''

#[[plugins]]
#repo = 'fatih/vim-go'
#on_ft = 'go'
