[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_lua = 'lspconfig'

#[[plugins]]
#repo = 'nvim-treesitter/nvim-treesitter'
#hook_post_update = 'TSUpdate'
#hook_source = 'source ~/.config/nvim/plugins/treesitter.rc.vim'
#
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']
hook_source = 'source ~/.config/nvim/plugins/telescope.rc.vim'
